# TRAINING PARAMETERS
WANDB_PROJECT: "larmatch-lmonly-cyclictest"
RESUME_FROM_CHECKPOINT: false
RESUME_OPTIM_FROM_CHECKPOINT: false
CHECKPOINT_FILE: "checkpoint.p1cmp075.sampled.26500th.tar"
LEARNING_RATE: 1.0e-1
WEIGHT_DECAY: 1.0e-6
NUM_ITERATIONS: 200000
START_ITER: 0
DEVICE: cuda
RUN_PROFILER: false
BATCH_SIZE: 10
BATCH_TRIPLET_LIMIT: 160000000
CLIP_GRAD_NORM: false
TRAIN_ITER_PER_RECORD: 10
TRAIN_ITER_PER_VALIDPT: 50
TRAIN_ITER_PER_FIXEDPT: 50
NUM_VALID_ITERS: 1
ITER_PER_CHECKPOINT: 500
ITER_PER_CACHECLEAR: 1
VERBOSE_MAIN_LOOP: false
VERBOSE_ITER_LOOP: false
VERBOSE_LOSS: false
VERBOSE_ACCURACY: false
MULTIPROCESS_BACKEND: "nccl"
MASTER_PORT: "12355"
CHECKPOINT_TAG: "p1cmp075.sampled"
USE_HARD_EXAMPLE_TRAINING: false

# DATASET PARAMETERS
NUM_TRIPLET_SAMPLES: 50000
#TRAIN_DATASET_INPUT_TXTFILE: "/cluster/tufts/wongjiradlabnu/twongj01/gen2/icdl/larflow/larmatchnet/larmatch/filelists/larmatchdata_comboned_reweight.train.list"
TRAIN_DATASET_INPUT_TXTFILE: "/home/twongjirad/working/larbys/icarus/icdl/larflow/larmatchnet/larmatch/test.list"
TRAIN_DATASET_VERBOSE: false
#VALID_DATASET_INPUT_TXTFILE: "/cluster/tufts/wongjiradlabnu/twongj01/gen2/icdl/larflow/larmatchnet/larmatch/filelists/larmatchdata_comboned_reweight.valid.list"
VALID_DATASET_INPUT_TXTFILE: "/home/twongjirad/working/larbys/icarus/icdl/larflow/larmatchnet/larmatch/test.list"
VALID_DATASET_VERBOSE: false
#FIXED_DATASET_INPUT_TXTFILE: "/cluster/tufts/wongjiradlabnu/twongj01/gen2/icdl/larflow/larmatchnet/larmatch/filelists/larmatchdata_comboned.fixed.list"
FIXED_DATASET_INPUT_TXTFILE: "/home/twongjirad/working/larbys/icarus/icdl/larflow/larmatchnet/larmatch/test.list"
FIXED_SAMPLE_BATCH_SIZE: 16
FIXED_DATASET_VERBOSE: false
USE_KEYPOINT_SAMPLER: false

# MODEL PARAMETERS
NUM_STEM_FEATURES: 16
NORM_LAYER: "batchnorm"

# LOSS PARAMETERS
USE_LEARNABLE_LOSS_WEIGHTS: false
RUN_LARMATCH: true
RUN_SSNET: false
RUN_KPLABEL: false
RUN_KPSHIFT: false
RUN_PAF: false
