# TRAINING PARAMETERS
RESUME_FROM_CHECKPOINT: true
RESUME_OPTIM_FROM_CHECKPOINT: true
CHECKPOINT_FILE: "checkpoint.ccgpu.notsampled.11000th.tar"
DEVICE: cuda
RUN_PROFILER: false
BATCH_SIZE: 1
BATCH_TRIPLET_LIMIT: 500000000

# MODEL PARAMETERS
NUM_STEM_FEATURES: 32
NORM_LAYER: "instance"
RUN_LARMATCH: true
RUN_SSNET: false
RUN_KPLABEL: true
RUN_KPSHIFT: false
RUN_PAF: false
