# TRAINING PARAMETERS
WANDB_PROJECT: "larmatchme-softlabels-v1"
#WANDB_PROJECT: "NONE"
RESUME_FROM_CHECKPOINT: false
RESUME_OPTIM_FROM_CHECKPOINT: false
CHECKPOINT_FILE: "/cluster/tufts/wongjiradlabnu/twongj01/gen2/icdl/larflow/larmatchnet/larmatch/checkpoints_lmonly/bumbling_snowball_26/checkpoint.p1cmp075.sampled.35500th.tar"
LEARNING_RATE: 5.0e-2
LEARNING_RATE_MIN: 1.0e-2
WEIGHT_DECAY: 1.0e-6
NUM_ITERATIONS: 200000
START_ITER: 0
DEVICE: cuda
RUN_PROFILER: false
BATCH_SIZE: 12
BATCH_TRIPLET_LIMIT: 300000000
CLIP_GRAD_NORM: false
TRAIN_ITER_PER_RECORD: 10
TRAIN_ITER_PER_VALIDPT: 50
TRAIN_ITER_PER_FIXEDPT: 50
NUM_VALID_ITERS: 1
ITER_PER_CHECKPOINT: 500
ITER_PER_CACHECLEAR: 1
VERBOSE_MAIN_LOOP: false
VERBOSE_ITER_LOOP: false
VERBOSE_LOSS: false
VERBOSE_ACCURACY: false
MULTIPROCESS_BACKEND: "nccl"
MASTER_PORT: "12355"
CHECKPOINT_TAG: "p1cmp075.sampled"
USE_HARD_EXAMPLE_TRAINING: false

# DATASET PARAMETERS
TRAIN_DATALOADER_CONFIG:
  NUM_TRIPLET_SAMPLES: 50000
  #INPUT_FILE: "/cluster/tufts/wongjiradlabnu/twongj01/gen2/icdl/larflow/larmatchnet/larmatch/filelists/larmatchdata_comboned_lmsoftlabels.train.list"
  INPUT_FILE: "/home/twongjirad/working/larbys/icarus/icdl/larflow/larmatchnet/larmatch/test.list"
  VERBOSE: false
  LOAD_TRUTH: true
  BATCHSIZE: 12
  USE_KEYPOINT_SAMPLER: false
  CONSTANT_SAMPLE: false
VALID_DATALOADER_CONFIG:
  NUM_TRIPLET_SAMPLES: 50000
  BATCHSIZE: 16
  LOAD_TRUTH: true  
  #INPUT_FILE: "/cluster/tufts/wongjiradlabnu/twongj01/gen2/icdl/larflow/larmatchnet/larmatch/filelists/larmatchdata_comboned_lmsoftlabels.valid.list"
  INPUT_FILE: "/home/twongjirad/working/larbys/icarus/icdl/larflow/larmatchnet/larmatch/test.list"
  VERBOSE: false
  USE_KEYPOINT_SAMPLER: false
  CONSTANT_SAMPLE: false  
FIXED_DATALOADER_CONFIG:
  NUM_TRIPLET_SAMPLES: 50000
  #INPUT_FILE: "/cluster/tufts/wongjiradlabnu/twongj01/gen2/icdl/larflow/larmatchnet/larmatch/filelists/larmatchdata_comboned_lmsoftlabels.fixed.list"
  INPUT_FILE: "/home/twongjirad/working/larbys/icarus/icdl/larflow/larmatchnet/larmatch/test.list"  
  BATCHSIZE: 16
  LOAD_TRUTH: true  
  VERBOSE: false
  USE_KEYPOINT_SAMPLER: false
  CONSTANT_SAMPLE: true  

# MODEL PARAMETERS
NUM_STEM_FEATURES: 32
NORM_LAYER: "batchnorm"

# LOSS PARAMETERS
USE_LEARNABLE_LOSS_WEIGHTS: false
RUN_LARMATCH: true
RUN_SSNET: false
RUN_KPLABEL: false
RUN_KPSHIFT: false
RUN_PAF: false
