# TRAINING PARAMETERS
WANDB_PROJECT: "larmatchme-nosample-kp+lm"
#WANDB_PROJECT: "NONE"
RESUME_FROM_CHECKPOINT: true
RESUME_OPTIM_FROM_CHECKPOINT: true
#CHECKPOINT_FILE: "/cluster/tufts/wongjiradlabnu/twongj01/gen2/icdl/larflow/larmatchnet/larmatch/checkpoint.ccgpu.notsampled.11000th.tar"
#CHECKPOINT_FILE: "/cluster/tufts/wongjiradlabnu/twongj01/gen2/icdl/larflow/larmatchnet/larmatch/checkpoints_larmatchme_nosample_kpandlm/amber-sky-13/checkpoint.p1cmp075.notsampled.11000th.tar"
CHECKPOINT_FILE: "/cluster/tufts/wongjiradlabnu/twongj01/gen2/icdl/larflow/larmatchnet/larmatch/checkpoints_larmatchme_nosample_kpandlm/smooth-jazz-15/checkpoint.p1cmp075.notsampled.13500th.tar"
LEARNING_RATE: 1.0e-4
LEARNING_RATE_MIN: 1.0e-4
WEIGHT_DECAY: 1.0e-6
NUM_ITERATIONS: 200000
START_ITER: 13501
DEVICE: cuda
RUN_PROFILER: false
BATCH_TRIPLET_LIMIT: 1000000
CLIP_GRAD_NORM: false
TRAIN_ITER_PER_RECORD: 10
TRAIN_ITER_PER_VALIDPT: 50
TRAIN_ITER_PER_FIXEDPT: 50
NUM_VALID_ITERS: 1
ITER_PER_CHECKPOINT: 500
ITER_PER_CACHECLEAR: 1
VERBOSE_MAIN_LOOP: false
VERBOSE_ITER_LOOP: false
VERBOSE_LOSS: false
VERBOSE_ACCURACY: false
MULTIPROCESS_BACKEND: "nccl"
MASTER_PORT: "12355"
CHECKPOINT_TAG: "p1cmp075.notsampled"
USE_HARD_EXAMPLE_TRAINING: false
WHOLE_BATCH: false

# MODEL PARAMETERS
NUM_STEM_FEATURES: 32
#NORM_LAYER: "batchnorm"
NORM_LAYER: "instance"

# DATASET PARAMETERS
TRAIN_DATALOADER_CONFIG:
  #NUM_TRIPLET_SAMPLES: 50000
  INPUT_FILE: "/cluster/tufts/wongjiradlabnu/twongj01/gen2/icdl/larflow/larmatchnet/larmatch/filelists/larmatchdata_comboned_fixednukp.train.list"
  #INPUT_FILE: "/home/twongjirad/working/larbys/icarus/icdl/larflow/larmatchnet/larmatch/test.list"
  VERBOSE: false
  LOAD_TRUTH: true
  BATCHSIZE: 4
  TRIPLET_LIMIT: 500000  
  USE_KEYPOINT_SAMPLER: false
  USE_QCUT_SAMPLER: true
  CONSTANT_SAMPLE: false
  NUM_WORKERS: 2
  RANDOM_ACCESS: true
VALID_DATALOADER_CONFIG:
  #NUM_TRIPLET_SAMPLES: 50000
  BATCHSIZE: 4
  TRIPLET_LIMIT: 500000  
  LOAD_TRUTH: true  
  INPUT_FILE: "/cluster/tufts/wongjiradlabnu/twongj01/gen2/icdl/larflow/larmatchnet/larmatch/filelists/larmatchdata_comboned_fixednukp.valid.list"
  #INPUT_FILE: "/home/twongjirad/working/larbys/icarus/icdl/larflow/larmatchnet/larmatch/test.list"
  VERBOSE: false
  USE_KEYPOINT_SAMPLER: false
  USE_QCUT_SAMPLER: true  
  CONSTANT_SAMPLE: false
  RANDOM_ACCESS: true  
FIXED_DATALOADER_CONFIG:
  #NUM_TRIPLET_SAMPLES: 50000
  INPUT_FILE: "/cluster/tufts/wongjiradlabnu/twongj01/gen2/icdl/larflow/larmatchnet/larmatch/filelists/larmatchdata_comboned_fixednukp.fixed.list"
  #INPUT_FILE: "/home/twongjirad/working/larbys/icarus/icdl/larflow/larmatchnet/larmatch/test.list"  
  BATCHSIZE: 4
  TRIPLET_LIMIT: 500000  
  LOAD_TRUTH: true  
  VERBOSE: false
  USE_KEYPOINT_SAMPLER: false
  USE_QCUT_SAMPLER: true  
  CONSTANT_SAMPLE: true
  RANDOM_ACCESS: true  

# LOSS PARAMETERS
USE_LEARNABLE_LOSS_WEIGHTS: true
RUN_LARMATCH: true
RUN_SSNET: false
RUN_KPLABEL: true
RUN_KPSHIFT: false
RUN_PAF: false
