# TRAINING PARAMETERS
RESUME_FROM_CHECKPOINT: true
RESUME_OPTIM_FROM_CHECKPOINT: true
CHECKPOINT_FILE: "checkpoint.4000th.tar"
LEARNING_RATE: 3.0e-4
WEIGHT_DECAY: 1.0e-4
NUM_ITERATIONS: 100000
START_ITER: 0
DEVICE: cuda
RUN_PROFILER: false
BATCH_SIZE: 3
BATCH_TRIPLET_LIMIT: 1500000
CLIP_GRAD_NORM: false
TRAIN_ITER_PER_RECORD: 1
TRAIN_ITER_PER_VALIDPT: 10
NUM_VALID_ITERS: 1
ITER_PER_CHECKPOINT: 500
ITER_PER_CACHECLEAR: 1
VERBOSE_MAIN_LOOP: false
VERBOSE_ITER_LOOP: false
VERBOSE_LOSS: false
VERBOSE_ACCURACY: false

# DATASET PARAMETERS
TRAIN_DATASET_INPUT_TXTFILE: "testdata.txt"
TRAIN_DATASET_VERBOSE: false
VALID_DATASET_INPUT_TXTFILE: "testdata.txt"
VALID_DATASET_VERBOSE: false

# MODEL PARAMETERS

# LOSS PARAMETERS
USE_LEARNABLE_LOSS_WEIGHTS: true
INIT_LM_LOSS_WEIGHT: -2.9
INIT_KP_LOSS_WEIGHT: -2.1
RUN_LARMATCH: true
RUN_SSNET: false
RUN_KPLABEL: true
RUN_KPSHIFT: false
RUN_PAF: false
