# TRAINING PARAMETERS
RESUME_FROM_CHECKPOINT: false
RESUME_OPTIM_FROM_CHECKPOINT: false
CHECKPOINT_FILE: "/cluster/tufts/wongjiradlabnu/twongj01/gen2/ubdl/larflow/larmatchnet/larmatch/checkpoint.14000th.tar"
LEARNING_RATE: 3.0e-4
WEIGHT_DECAY: 1.0e-4
NUM_ITERATIONS: 100000
START_ITER: 0
DEVICE: cuda
RUN_PROFILER: false
BATCH_SIZE: 4
BATCH_TRIPLET_LIMIT: 33000000
CLIP_GRAD_NORM: false
TRAIN_ITER_PER_RECORD: 1
TRAIN_ITER_PER_VALIDPT: 10
NUM_VALID_ITERS: 1
ITER_PER_CHECKPOINT: 1000
ITER_PER_CACHECLEAR: 1
VERBOSE_MAIN_LOOP: false
VERBOSE_ITER_LOOP: false
VERBOSE_LOSS: true
VERBOSE_ACCURACY: false
LOGGER: "wandb"

# DATASET PARAMETERS
TRAIN_DATASET_INPUT_TXTFILE: "/cluster/tufts/wongjiradlabnu/twongj01/gen2/photon_analysis/ubdl/larflow/larmatchnet/larmatch/cache_list_larmatch_training_dataset.txt"
#TRAIN_DATASET_INPUT_TXTFILE: "test_h5data.txt"
TRAIN_DATASET_VERBOSE: false
TRAIN_DATASET_LOAD_FROM_CACHE: true
VALID_DATASET_INPUT_TXTFILE: "/cluster/tufts/wongjiradlabnu/twongj01/gen2/photon_analysis/ubdl/larflow/larmatchnet/larmatch/cache_list_larmatch_validation_dataset.txt"
#VALID_DATASET_INPUT_TXTFILE: "test_h5data.txt"
VALID_DATASET_LOAD_FROM_CACHE: true
VALID_DATASET_VERBOSE: false
NUM_TRAIN_WORKERS: 4
NUM_VALID_WORKERS: 1

# MODEL PARAMETERS

# LOSS PARAMETERS
USE_LEARNABLE_LOSS_WEIGHTS: true
RUN_LARMATCH: true
RUN_SSNET: true
RUN_KPLABEL: true
RUN_KPSHIFT: false
RUN_PAF: true
