# TRAINING PARAMETERS
RESUME_FROM_CHECKPOINT: false
RESUME_OPTIM_FROM_CHECKPOINT: false
CHECKPOINT_FILE: "/cluster/tufts/wongjiradlabnu/twongj01/gen2/ubdl/larflow/larmatchnet/larmatch/checkpoint.14000th.tar"
LEARNING_RATE: 1.0e-2
WEIGHT_DECAY: 1.0e-4
NUM_ITERATIONS: 1000000
START_ITER: 0
DEVICE: cuda
RUN_PROFILER: false
BATCH_SIZE: 8
BATCH_TRIPLET_LIMIT: 3300000
CLIP_GRAD_NORM: false
TRAIN_ITER_PER_RECORD: 1
TRAIN_ITER_PER_VALIDPT: 10
NUM_VALID_ITERS: 1
ITER_PER_CHECKPOINT: 1000
ITER_PER_CACHECLEAR: 1
VERBOSE_MAIN_LOOP: false
VERBOSE_ITER_LOOP: false
VERBOSE_LOSS: false
VERBOSE_ACCURACY: false
CHECKPOINT_TAG: "a100"

# DATASET PARAMETERS
TRAIN_DATASET_INPUT_TXTFILE: "/cluster/tufts/wongjiradlabnu/twongj01/gen2/icdl/larflow/larmatchnet/larmatch/filelists/larmatchdata_comboned.train.list"
TRAIN_DATASET_VERBOSE: false
VALID_DATASET_INPUT_TXTFILE: "/cluster/tufts/wongjiradlabnu/twongj01/gen2/icdl/larflow/larmatchnet/larmatch/filelists/larmatchdata_comboned.valid.list"
VALID_DATASET_VERBOSE: false

# MODEL PARAMETERS

# LOSS PARAMETERS
USE_LEARNABLE_LOSS_WEIGHTS: true
RUN_LARMATCH: true
RUN_SSNET: true
RUN_KPLABEL: true
RUN_KPSHIFT: false
RUN_PAF: false
