# TRAINING PARAMETERS
RESUME_FROM_CHECKPOINT: false
RESUME_OPTIM_FROM_CHECKPOINT: false
CHECKPOINT_FILE: "test.tar"
LEARNING_RATE: 1.0e-2
WEIGHT_DECAY: 1.0e-4
NUM_ITERATIONS: 100
START_ITER: 0
DEVICE: cuda
RUN_PROFILER: true
BATCH_SIZE: 2
CLIP_GRAD_NORM: false
TRAIN_ITER_PER_RECORD: 1
TRAIN_ITER_PER_VALIDPT: 5
NUM_VALID_ITERS: 1
ITER_PER_CHECKPOINT: 10

# DATASET PARAMETERS
TRAIN_DATASET_INPUT_TXTFILE: "testdata.txt"
TRAIN_DATASET_VERBOSE: true
VALID_DATASET_INPUT_TXTFILE: "testdata.txt"
VALID_DATASET_VERBOSE: true

# MODEL PARAMETERS

# LOSS PARAMETERS
RUN_SSNET: true
RUN_KPLABEL: true
RUN_KPSHIFT: true
RUN_PAF: true
LOSS_VERBOSE: true
