# TRAINING PARAMETERS
RESUME_FROM_CHECKPOINT: true
RESUME_OPTIM_FROM_CHECKPOINT: true
CHECKPOINT_FILE: "checkpoint.p1cmp075.sampled.7500th.tar"
DEVICE: cuda
RUN_PROFILER: false
BATCH_SIZE: 3
BATCH_TRIPLET_LIMIT: 1500000

# MODEL PARAMETERS
NUM_STEM_FEATURES: 32
NORM_LAYER: "batchnorm"
RUN_LARMATCH: true
RUN_SSNET: false
RUN_KPLABEL: false
RUN_KPSHIFT: false
RUN_PAF: false
