TRAIN_DATALOADER_CONFIG:
  INPUT_FILE: "test.list"
  NUM_TRIPLET_SAMPLES: 100000
  LOAD_TRUTH: true
  VERBOSE: false
  BATCHSIZE: 4
  USE_KEYPOINT_SAMPLER: true
  CONSTANT_SAMPLE: false
  RANDOM_ACCESS: false
