# TRAINING PARAMETERS
# MODEL PARAMETERS
RUN_LARMATCH: true
RUN_KPLABEL: true
RUN_SSNET: false
RUN_KPSHIFT: false
RUN_PAF: false
CHECKPOINT_FILE: "checkpoint.cc1gpu.78000th.tar"
# PARAMETERS THAT CONFIG HOW TO READ THE INPUT
LARCV_ADC_NAME: "wire"
LARCV_CHSTATUS_NAME: "wire"
LARCV_HAS_WIRECELL: True
LARCV_TICKBACKWARDS: True
