DEVICE: "cuda"
RESUME_FROM_CHECKPOINT: true
RESUME_OPTIM_FROM_CHECKPOINT: true
CHECKPOINT_FILE: "lv.classify.checkpoint.3000th.tar"
WEIGHT_DECAY: 1.0e-4
LEARNING_RATE: 1.0e-4
DETECT_ANOMALY: false
RUNPROFILER: false
NUM_ITERATIONS: 10000
START_ITER: 3001
LOSS_VERBOSE: false
ITER_PER_CHECKPOINT: 1000
TRAIN_ITER_PER_RECORD: 1
TRAIN_ITER_PER_VALIDPT: 10
NUM_VALID_ITERS: 1

INPUT_TXTFILE_TRAIN: "testdata.txt"
INPUT_TXTFILE_VALID: "testdata.txt"
BATCHSIZE_TRAIN: 16
BATCHSIZE_VALID: 16

