add_subdirectory(LArFlowConstants)
add_subdirectory(RecoUtils)
add_subdirectory(PrepFlowMatchData)
add_subdirectory(KeyPoints)
add_subdirectory(OpticalModel)
add_subdirectory(Voxelizer)
add_subdirectory(SCBoundary)
#if (larpid_FOUND)
#  add_subdirectory(ProngCNN)
#endif()
add_subdirectory(Reco)
add_subdirectory(HDF5utils)

#add_subdirectory(MCTools)
# #add_subdirectory(FlowContourMatch)
#add_subdirectory(CRTMatch)
#add_subdirectory(MaskRCNNreco)
# add_subdirectory(SpatialEmbed)
# add_subdirectory(DETR)
# add_subdirectory(CosmicRemovalSuite)
