# CONFIG FOR train_kps_larmath

GPUMODE: True
DEVICE: "cuda:0"
RESUME_FROM_CHECKPOINT: True
RESUME_OPTIM_FROM_CHECKPOINT:  True
RUNPROFILER: False
CHECKPOINT_FILE: "/cluster/tufts/wongjiradlabnu/twongj01/gen2/ubdl/larflow/larmatchnet/lv.multidecoder.checkpoint.10600th.tar"
#CHECKPOINT_FILE: "checkpoint.75000th.tar"
RUN_SSNET: True
RUN_KPLABEL: True
TRAIN_VERBOSE: False
LOSS_VERBOSE: False
FREEZE_LAYERS: []
LEARNING_RATE: 1.0e-5
WEIGHT_DECAY: 1.0e-4
SSNET_CLASS_NAMES: ["bg","electron","gamma","muon","pion","proton","other"]

# TRAINING+VALIDATION DATA PATHS
# ================================
#INPUT_TXTFILE_TRAIN: test_voxel_train.txt
#INPUT_TXTFILE_VALID: test_voxel_valid.txt
INPUT_TXTFILE_TRAIN: "/cluster/tufts/wongjiradlabnu/twongj01/gen2/ubdl/larflow/larmatchnet/training_set_voxeldata.txt"
INPUT_TXTFILE_VALID: "/cluster/tufts/wongjiradlabnu/twongj01/gen2/ubdl/larflow/larmatchnet/validation_set_voxeldata.txt"

# TRAINING PARAMETERS
# =======================
START_ITER: 10600
NUM_ITERATIONS: 100000
TRAIN_ITER_PER_RECORD: 1
TRAIN_ITER_PER_VALIDPT: 50
NUM_VALID_ITERS: 5

BATCHSIZE_TRAIN: 32  # batches per training iteration
BATCHSIZE_VALID: 4  # batches per validation iteration

# CHECKPOINT PARAMETERS
# =======================
DEVICE_IDS: [0]
# map multi-training weights 
CHECKPOINT_MAP_LOCATIONS: None
CHECKPOINT_FROM_DATA_PARALLEL: False
ITER_PER_CHECKPOINT: 200
PREDICT_CLASSVEC: True
