# CONFIG FOR train_kps_larmath

GPUMODE: True
DEVICE: "cuda:0"

# TRAINING CONFIG
# =================
RESUME_FROM_CHECKPOINT: False
RESUME_OPTIM_FROM_CHECKPOINT:  False
RUNPROFILER: False
#CHECKPOINT_FILE: "/cluster/tufts/wongjiradlabnu/twongj01/gen2/ubdl/larflow/larmatchnet/checkpoint.15000th.tar"
CHECKPOINT_FILE: "checkpoint.75000th.tar"
TRAIN_VERBOSE: False
LOSS_VERBOSE: False
FREEZE_LAYERS: []
LEARNING_RATE: 1.0e-3
WEIGHT_DECAY: 1.0e-4

# MODEL CONFIG
# =====================
MODEL_TYPE: "unet"
RUN_SSNET: True
RUN_KPLABEL: True
SSNET_CLASS_NAMES: ["bg","electron","gamma","muon","pion","proton","other"]

# TRAINING+VALIDATION DATA PATHS
# ================================
#INPUT_TXTFILE_TRAIN: test_train.txt
#INPUT_TXTFILE_VALID: test_valid.txt
INPUT_TXTFILE_TRAIN: "/cluster/tufts/wongjiradlabnu/twongj01/gen2/ubdl/larflow/larmatchnet/training_set_voxeldata.txt"
INPUT_TXTFILE_VALID: "/cluster/tufts/wongjiradlabnu/twongj01/gen2/ubdl/larflow/larmatchnet/validation_set_voxeldata.txt"

# TRAINING PARAMETERS
# =======================
START_ITER: 0
NUM_ITERATIONS: 100000
TRAIN_ITER_PER_RECORD: 1
TRAIN_ITER_PER_VALIDPT: 50
NUM_VALID_ITERS: 1

BATCHSIZE_TRAIN: 16  # batches per training iteration
BATCHSIZE_VALID: 16  # batches per validation iteration

# CHECKPOINT PARAMETERS
# =======================
DEVICE_IDS: [0]
# map multi-training weights 
CHECKPOINT_MAP_LOCATIONS: None
CHECKPOINT_FROM_DATA_PARALLEL: False
ITER_PER_CHECKPOINT: 1000
PREDICT_CLASSVEC: True
