# CONFIG FOR train_kps_larmath

GPUMODE: True
DEVICE: "cuda:0"
RESUME_FROM_CHECKPOINT: False
RESUME_OPTIM_FROM_CHECKPOINT: False
RUNPROFILER: False
CHECKPOINT_FILE: "train_kps_no_ssnet/checkpoint.1262000th.tar"
EXCLUDE_NEG_EXAMPLES: False
RUN_SSNET: True
RUN_KPLABEL: True
RUN_KPSHIFT: False
RUN_PAF: True
TRAIN_VERBOSE: False
FREEZE_LAYERS: []
LEARNING_RATE: 1.0e-2
WEIGHT_DECAY: 1.0e-4
#FREEZE_LAYERS: ["larmatch","ssnet","kpshift"]:
SSNET_CLASS_NAMES: ["bg","electron","gamma","muon","pion","proton","other"]

# TRAINING+VALIDATION DATA PATHS
# ================================
TRAIN_DATA_FOLDER: "/cluster/tufts/wongjiradlabnu/twongj01/gen2/ubdl/larflow/larmatchnet/"
#TRAIN_DATA_FOLDER: "/home/twongjirad/working/data/larmatch_training_data/"
INPUTFILE_TRAIN: ["./larmatchtriplet_ana_trainingdata_testfile.root"]
INPUTFILE_VALID: ["./larmatchtriplet_ana_trainingdata_testfile.root"]

# TRAINING PARAMETERS
# =======================
START_ITER: 0
NUM_ITERATIONS: 2000
TEST_NUM_MATCH_PAIRS: 100000
ADC_MAX: 400.0
TRAIN_ITER_PER_RECORD: 5
TRAIN_ITER_PER_VALIDPT: 10
NUM_VALID_ITERS: 10

BATCHSIZE_TRAIN: 1  # batches per training iteration
BATCHSIZE_VALID: 1  # batches per validation iteration

# CHECKPOINT PARAMETERS
# =======================
DEVICE_IDS: [0]
# map multi-training weights 
CHECKPOINT_MAP_LOCATIONS: {"cuda:0":"cuda:0",
                           "cuda:1":"cuda:1"}
HARDEX_MAP_LOCATIONS: {"cuda:0":"cuda:0",
                       "cuda:1":"cuda:1"}
CHECKPOINT_MAP_LOCATIONS: None
CHECKPOINT_FROM_DATA_PARALLEL: False
ITER_PER_CHECKPOINT: 1000
PREDICT_CLASSVEC: True
